# common settings for all environments
version: "3"
services: 
    nginx:
        image: nginx:stable-alpine 
        depends_on: 
            - node-app
        volumes: 
            # ovveride default nginx template and use mine
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app: 
        # build using dockerfile in current dir
        build: .
        environment:
            - PORT=3000
        depends_on: 
            - mongo
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: anish
            MONGO_INITDB_ROOT_PASSWORD: mypassword
        volumes: 
            # named volume; must be declared in volumes section
            - mongo-db:/data/db   
    redis:
        image: redis
        
volumes: 
    mongo-db: