version: "3"
services: 
    node-app: 
        build: 
            # location of dockerfile
            context: .
            args: 
                NODE_ENV: development
        volumes:
            # bind mount
            - ./:/app
            # anonymous volume to prevent overwrite
            - /app/node_modules 
        environment:
            - NODE_ENV=development
        command: npm run dev
            
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: anish
            ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword   