version: "3"
services: 
    nginx:
        ports: 
            # serve on port 80 in prod
            - "80:80"
    node-app: 
        # swarm related: https://docs.docker.com/compose/compose-file/compose-file-v3/#deploy
        deploy:
            replicas: 8
            restart_policy: 
                condition: any
            updated_config:
                parallelism: 2
                delay: 15s
        build: 
            # location of dockerfile
            context: .
            args: 
                NODE_ENV: production        
        environment:
            - NODE_ENV=production
            # PULL values from env vars
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}
        command: node index.js
    mongo:
        environment:
            # YOU Can set env var by export varid=value
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}    